name: Auto Commit

on:
  push:
    branches:
      - update-autocommit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: update-autocommit
        fetch-depth: 0

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Set up Git
      run: |
        git config user.name "Oleg Kizyma"
        git config user.email "oleg1203@gmail.com"

    - name: Check and commit unfinished changes
      run: |
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git add -A
          git reset .backups/
          git commit -m "Auto-commit: Unfinished changes" -m "Changes description:\n- Automated cleanup of unfinished changes" || echo "No changes to commit"
        fi

    - name: Check for incomplete commits
      run: |
        if git status --porcelain | grep -q '^??'; then
          git add -A
          git reset .backups/
          git commit -m "Auto-commit: Add untracked files" -m "Changes description:\n- Adding previously untracked files" || echo "No untracked files to commit"
        fi

    - name: Push changes
      run: git push || echo "No changes to push"